version: '3.9'

services:
  app:
    build:
      context: ./backend
    container_name: app
    volumes:
      - ./backend:/var/www/backend
    working_dir: /var/www/backend
    ports:
      - "8000:8000"
    command: >
      sh -c "
        until php artisan migrate --force; do
          echo 'Esperando la base de datos...'
          sleep 2
        done &&
        php-fpm
      "
    expose:
      - "9000"
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx_server
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www/backend
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

  db:
    image: postgres:16
    container_name: db
    restart: always
    environment:
      POSTGRES_DB: licoreria
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Admin_2025
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge